accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogOutView.as_view(), name='logout'),
    path('signup/', views.SignUpView.as_view(), name='signup'),
]

djangoProject5/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls')),
    path('blog/', include('blog.urls')),
    path('accounts/', include('accounts.urls')),
    path('summernote/', include('django_summernote.urls')),
    path('captcha/', include('captcha.urls')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/urls.py
from django.urls import path
from . import views

app_name = 'website'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('about/', views.AboutView.as_view(), name='about'),
    path('contact/', views.ContactView.as_view(), name='contact'),
    path('newsletter/', views.NewsLetterView.as_view(), name='newsletter'),
]

accounts/models.py
from django.db import models

# Create your models here.

website/models.py
from django.db import models


class Contact(models.Model):
    name = models.CharField(max_length=255)
    email = models.EmailField()
    subject = models.CharField(max_length=255)
    message = models.TextField()
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-created_date']

    def __str__(self):
        return self.name


class Newsletter(models.Model):
    email = models.EmailField()

    def __str__(self):
        return self.email

website/forms.py
from django import forms
from .models import *


class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = '__all__'


class NewsLetterForm(forms.ModelForm):
    class Meta:
        model = Newsletter
        fields = '__all__'

accounts/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render, redirect
from django.views import View
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm


class LoginView(View):
    def setup(self, request, *args, **kwargs):
        self.next = request.GET.get('next')
        return super().setup(request, *args, **kwargs)

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect('website:index')
        return super().dispatch(request, *args, **kwargs)

    def get(self, request):
        form = AuthenticationForm()
        context = {'form': form}
        return render(request, 'accounts/login.html', context)

    def post(self, request):
        form = AuthenticationForm(request=request, data=request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(request, username=cd['username'], password=cd['password'])

            if user is not None:
                login(request, user)
                if self.next:
                    return redirect(self.next)

            return redirect('website:index')
        messages.error(request, 'The information entered is incorrect')
        return render(request, 'accounts/login.html')


class LogOutView(LoginRequiredMixin, View):
    def get(self, request):
        logout(request)
        return redirect('website:index')


class SignUpView(View):
    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect('website:index')
        return super().dispatch(request, *args, **kwargs)

    def get(self, request):
        form = UserCreationForm()
        context = {'form': form}
        return render(request, 'accounts/signup.html', context)

    def post(self, request):
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('website:index')

        else:
            context = {'form': form}
            return render(request, 'accounts/signup.html', context)

website/views.py
from django.shortcuts import render, redirect
from django.views import View
from .forms import *
from django.contrib import messages
from blog.models import *


class IndexView(View):
    def get(self, request):
        posts = Post.objects.filter(status=1)
        latest_posts = posts[0:min(6, posts.count())]
        context = {'latest_posts': latest_posts}
        return render(request, 'website/index.html', context)


class AboutView(View):
    def get(self, request):
        return render(request, 'website/about.html')


class ContactView(View):
    def get(self, request):
        form = ContactForm()
        context = {'form': form}
        return render(request, 'website/contact.html', context)

    def post(self, request):
        form = ContactForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'your ticket submitted successfully')
        else:
            messages.ERROR(request, 'your ticket didnt submitted ')

        return render(request, 'website/contact.html')


class NewsLetterView(View):
    def post(self, request):
        form = NewsLetterForm(request.POST)
        if form.is_valid():
            form.save()
        referer = request.META.get('HTTP_REFERER')
        return redirect(referer)

templates/accounts/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
</head>
<body>
<div class="p-5" style="background-color:#9A616D; "></div>
<section class="vh-100" style="background-color: #9A616D;">
    <div class="container py-5 h-100">
        <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="col col-xl-10">
                <div class="card" style="border-radius: 1rem;">
                    <div class="row g-0">
                        <div class="col-md-6 col-lg-5 d-none d-md-block">
                            <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-login-form/img1.webp"
                                 alt="login form" class="img-fluid" style="border-radius: 1rem 0 0 1rem;"/>
                        </div>
                        <div class="col-md-6 col-lg-7 d-flex align-items-center">
                            <div class="card-body p-4 p-lg-5 text-black">

                                <form method="post">
                                    {% csrf_token %}
                                    <div class="d-flex align-items-center mb-3 pb-1">
                                        <i class="fas fa-cubes fa-2x me-3" style="color: #ff6219;"></i>
                                        <span class="h1 fw-bold mb-0">Login</span>
                                    </div>

                                    <h5 class="fw-normal mb-3 pb-3" style="letter-spacing: 1px;">login into your
                                        account</h5>

                                    <div data-mdb-input-init class="form-outline mb-4">
                                        <label class="form-label" for="form2Example17">username</label>
                                        <input type="text" name="username" id="form2Example17"
                                               class="form-control form-control-lg"/>

                                    </div>

                                    <div data-mdb-input-init class="form-outline mb-4">
                                        <label class="form-label" for="form2Example27">password</label>
                                        <input type="password" name="password" id="form2Example27"
                                               class="form-control form-control-lg"/>

                                    </div>

                                    <div class="pt-1 mb-4">
                                        <button data-mdb-button-init data-mdb-ripple-init
                                                class="btn btn-dark btn-lg btn-block" type="submit">Login
                                        </button>
                                    </div>

                                </form>
                                {% if messages %}
                                    <ul class="messages">
                                        {% for message in messages %}
                                            <li{% if message.tags %}
                                                class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                                        {% endfor %}
                                    </ul>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<div class="p-5" style="background-color:#9A616D; "></div>
<div class="p-5" style="background-color:#9A616D; "></div>
</body>
</html>

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="zxx" class="no-js">
<head>
    <!-- Mobile Specific Meta -->
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Favicon-->
    <link rel="shortcut icon" href="{% static 'img/fav.png' %}">
    <!-- Author Meta -->
    <meta name="author" content="colorlib">
    <!-- Meta Description -->
    <meta name="description" content="">
    <!-- Meta Keyword -->
    <meta name="keywords" content="">
    <!-- meta character set -->
    <meta charset="UTF-8">
    <!-- Site Title -->
    <title>Travel</title>

    <link href="https://fonts.googleapis.com/css?family=Poppins:100,200,400,300,500,600,700" rel="stylesheet">
    <!--
    CSS
    ============================================= -->
    <link rel="stylesheet" href="{% static 'css/linearicons.css' %}">
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">
    <link rel="stylesheet" href="{% static 'css/jquery-ui.css' %}">
    <link rel="stylesheet" href="{% static 'css/nice-select.css' %}">
    <link rel="stylesheet" href="{% static 'css/animate.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.css' %}">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    {% block head %}{% endblock %}
</head>
<body>
<header id="header">
    <div class="header-top">
        <div class="container">
            <div class="row align-items-center">
                <div class="col-lg-6 col-sm-6 col-6 header-top-left">
                    <ul>
                        {% if request.user.is_authenticated %}
                            <li><a href="#">login as {{ request.user.username }}</a></li>
                            <li><a href="{% url 'accounts:logout' %}">Logout</a></li>
                        {% else %}
                            <li><a href="{% url 'accounts:login' %}">Login</a></li>
                            <li><a href="{% url 'accounts:signup' %}">Sign Up</a></li>
                        {% endif %}
                    </ul>
                </div>
                <div class="col-lg-6 col-sm-6 col-6 header-top-right">
                    <div class="header-social">
                        <a href="#"><i class="fa fa-facebook"></i></a>
                        <a href="#"><i class="fa fa-twitter"></i></a>
                        <a href="#"><i class="fa fa-dribbble"></i></a>
                        <a href="#"><i class="fa fa-behance"></i></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="container main-menu">
        <div class="row align-items-center justify-content-between d-flex">
            <div id="logo">
                <a href="{% url 'website:index' %}"><img src="{% static 'img/logo.png' %}" alt="" title=""/></a>
            </div>
            <nav id="nav-menu-container">
                <ul class="nav-menu">
                    <li><a href="{% url 'website:index' %}">Home</a></li>
                    <li><a href="{% url 'website:about' %}">About</a></li>
                    <li><a href="{% url 'blog:blog' %}">Blog</a></li>
                    <li><a href="{% url 'website:contact' %}">Contact</a></li>
                </ul>
            </nav><!-- #nav-menu-container -->
        </div>
    </div>
</header><!-- #header -->
{% block body %}{% endblock %}

<!-- start footer Area -->
<footer class="footer-area section-gap">
    <div class="container">

        <div class="row">
            <div class="col-lg-3  col-md-6 col-sm-6">
                <div class="single-footer-widget">
                    <h6>About Agency</h6>
                    <p>
                        The world has become so fast paced that people don’t want to stand by reading a page of
                        information, they would much rather look at a presentation and understand the message. It has
                        come to a point
                    </p>
                </div>
            </div>
            <div class="col-lg-3 col-md-6 col-sm-6">
                <div class="single-footer-widget">
                    <h6>Navigation Links</h6>
                    <div class="row">
                        <div class="col">
                            <ul>
                                <li><a href="#">Home</a></li>
                                <li><a href="#">Feature</a></li>
                                <li><a href="#">Services</a></li>
                                <li><a href="#">Portfolio</a></li>
                            </ul>
                        </div>
                        <div class="col">
                            <ul>
                                <li><a href="#">Team</a></li>
                                <li><a href="#">Pricing</a></li>
                                <li><a href="#">Blog</a></li>
                                <li><a href="#">Contact</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-3  col-md-6 col-sm-6">
                <div class="single-footer-widget">
                    <h6>Newsletter</h6>
                    <p>
                        For business professionals caught between high OEM price and mediocre print and graphic output.
                    </p>
                    <div>
                        <form
                                action="{% url 'website:newsletter' %}"
                                method="post" class="subscription relative">
                            {% csrf_token %}
                            <div class="input-group d-flex flex-row">
                                <input name="email" placeholder="Email Address" onfocus="this.placeholder = ''"
                                       onblur="this.placeholder = 'Email Address '" required="" type="email">
                                <button class="btn bb-btn"><span class="lnr lnr-location"></span></button>
                            </div>
                            <div class="mt-10 info"></div>
                        </form>
                    </div>
                </div>
            </div>
            <div class="col-lg-3  col-md-6 col-sm-6">
                <div class="single-footer-widget mail-chimp">
                    <h6 class="mb-20">InstaFeed</h6>
                    <ul class="instafeed d-flex flex-wrap">
                        <li><img src="{% static 'img/i1.jpg' %}" alt=""></li>
                        <li><img src="{% static 'img/i2.jpg' %}" alt=""></li>
                        <li><img src="{% static 'img/i3.jpg' %}" alt=""></li>
                        <li><img src="{% static 'img/i4.jpg' %}" alt=""></li>
                        <li><img src="{% static 'img/i5.jpg' %}" alt=""></li>
                        <li><img src="{% static 'img/i6.jpg' %}" alt=""></li>
                        <li><img src="{% static 'img/i7.jpg' %}" alt=""></li>
                        <li><img src="{% static 'img/i8.jpg' %}" alt=""></li>
                    </ul>
                </div>
            </div>
        </div>

        <div class="row footer-bottom d-flex justify-content-between align-items-center">
            <p class="col-lg-8 col-sm-12 footer-text m-0">
                <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                Copyright &copy;<script>document.write(new Date().getFullYear());</script>
                All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a
                    href="https://colorlib.com" target="_blank">Colorlib</a>
                <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p>
            <div class="col-lg-4 col-sm-12 footer-social">
                <a href="#"><i class="fa fa-facebook"></i></a>
                <a href="#"><i class="fa fa-twitter"></i></a>
                <a href="#"><i class="fa fa-dribbble"></i></a>
                <a href="#"><i class="fa fa-behance"></i></a>
            </div>
        </div>
    </div>
</footer>
<!-- End footer Area -->

<script src="{% static 'js/vendor/jquery-2.2.4.min.js' %}"></script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/vendor/bootstrap.min.js' %}"></script>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBhOdIF3Y9382fqJYt5I_sswSrEw5eihAA"></script>
<script src="{% static 'js/jquery-ui.js' %}"></script>
<script src="{% static 'js/easing.min.js' %}"></script>
<script src="{% static 'js/hoverIntent.js' %}"></script>
<script src="{% static 'js/superfish.min.js' %}"></script>
<script src="{% static 'js/jquery.ajaxchimp.min.js' %}"></script>
<script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
<script src="{% static 'js/jquery.nice-select.min.js' %}"></script>
<script src="{% static 'js/owl.carousel.min.js' %}"></script>
<script src="{% static 'js/mail-script.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>
</body>
</html>

templates/blog/blog-latest-posts.html
{% load static %}
<div class="single-sidebar-widget popular-post-widget">
    <h4 class="popular-title">Latest Posts</h4>
    <div class="popular-post-list">
        {% for post in lasted_posts %}
        <div class="single-post-list d-flex flex-row align-items-center">
            <div class="thumb">
                <img class="img-fluid" src="{{ post.image.url }}" alt="" style="height: 60px;width: 80px">
            </div>
            <div class="details">
                <a href="{% url 'blog:blog_single' post.id %}"><h6>{{ post.title | truncatewords:3 }}</h6></a>
                <p>{{ post.published_date | timesince  }}</p>
            </div>
        </div>
        {% endfor %}
    </div>
</div>

templates/blog/blog-post-category.html
<div class="single-sidebar-widget post-category-widget">
    <h4 class="category-title">Post Catgories</h4>
    <ul class="cat-list">
        {% for name,value in cat_dict.items %}
        <li>
            <a href="{% url 'blog:blog_category' name %}" class="d-flex justify-content-between">
                <p>{{ name }}</p>
                <p>{{ value }}</p>
            </a>
        </li>
        {% endfor %}
    </ul>
</div>

templates/blog/blog-writer.html
{% load static %}
<div class="single-sidebar-widget user-info-widget">
    <img src="{% static 'img/blog/user-info.png' %}" alt="">
    <a href="#"><h4>davoudi</h4></a>
    <p>
        Senior blog writer
    </p>
    <ul class="social-links">
        <li><a href="#"><i class="fa fa-facebook"></i></a></li>
        <li><a href="#"><i class="fa fa-twitter"></i></a></li>
        <li><a href="#"><i class="fa fa-github"></i></a></li>
        <li><a href="#"><i class="fa fa-behance"></i></a></li>
    </ul>
    <p>
        Boot camps have its supporters andit sdetractors. Some people do not understand why you
        should have to spend money on boot camp when you can get. Boot camps have itssuppor ters
        andits detractors.
    </p>
</div>

templates/website/about.html
{% extends 'base.html' %}
{% load static %}
{% block body %}

    <!-- start banner Area -->
    <section class="about-banner relative">
        <div class="overlay overlay-bg"></div>
        <div class="container">
            <div class="row d-flex align-items-center justify-content-center">
                <div class="about-content col-lg-12">
                    <h1 class="text-white">
                        About Us
                    </h1>
                    <p class="text-white link-nav"><a href="{% url 'website:index' %}">Home </a> <span
                            class="lnr lnr-arrow-right"></span> <a href="{% url 'website:about' %}"> About Us</a></p>
                </div>
            </div>
        </div>
    </section>
    <!-- End banner Area -->

    <!-- Start about-info Area -->
    <section class="about-info-area section-gap">
        <div class="container">
            <div class="row align-items-center">
                <div class="col-lg-6 info-left">
                    <img class="img-fluid" src="{% static 'img/about/info-img.jpg' %}" alt="">
                </div>
                <div class="col-lg-6 info-right">
                    <h6>About Us</h6>
                    <h1>Who We Are?</h1>
                    <p>
                        Here, I focus on a range of items and features that we use in life without giving them a second
                        thought. such as Coca Cola. Dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor
                        incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation
                        ullamco.
                    </p>
                </div>
            </div>
        </div>
    </section>
    <!-- End about-info Area -->

    <!-- Start other-issue Area -->
    <section class="other-issue-area section-gap">
        <div class="container">
            <div class="row d-flex justify-content-center">
                <div class="menu-content pb-70 col-lg-9">
                    <div class="title text-center">
                        <h1 class="mb-10">Other issues we can help you with</h1>
                        <p>We all live in an age that belongs to the young at heart. Life that is.</p>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-3 col-md-6">
                    <div class="single-other-issue">
                        <div class="thumb">
                            <img class="img-fluid" src="{% static 'img/o1.jpg' %}" alt="">
                        </div>
                        <a href="#">
                            <h4>Rent a Car</h4>
                        </a>
                        <p>
                            The preservation of human life is the ultimate value, a pillar of ethics and the foundation.
                        </p>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6">
                    <div class="single-other-issue">
                        <div class="thumb">
                            <img class="img-fluid" src="{% static 'img/o2.jpg' %}" alt="">
                        </div>
                        <a href="#">
                            <h4>Cruise Booking</h4>
                        </a>
                        <p>
                            I was always somebody who felt quite sorry for myself, what I had not got compared.
                        </p>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6">
                    <div class="single-other-issue">
                        <div class="thumb">
                            <img class="img-fluid" src="{% static 'img/o3.jpg' %}" alt="">
                        </div>
                        <a href="#">
                            <h4>To Do List</h4>
                        </a>
                        <p>
                            The following article covers a topic that has recently moved to center stage–at least it
                            seems.
                        </p>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6">
                    <div class="single-other-issue">
                        <div class="thumb">
                            <img class="img-fluid" src="{% static 'img/o4.jpg' %}" alt="">
                        </div>
                        <a href="#">
                            <h4>Food Features</h4>
                        </a>
                        <p>
                            There are many kinds of narratives and organizing principles. Science is driven by evidence.
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- End other-issue Area -->
{% endblock %}

templates/website/contact.html
{% extends 'base.html' %}
{% load static %}
{% block body %}
    <!-- start banner Area -->
    <section class="relative about-banner">
        <div class="overlay overlay-bg"></div>
        <div class="container">
            <div class="row d-flex align-items-center justify-content-center">
                <div class="about-content col-lg-12">
                    <h1 class="text-white">
                        Contact Us
                    </h1>
                    <p class="text-white link-nav"><a href="{% url 'website:index' %}">Home </a> <span
                            class="lnr lnr-arrow-right"></span> <a href="{% url 'website:contact' %}"> Contact Us</a>
                    </p>
                </div>
            </div>
        </div>
    </section>
    <!-- End banner Area -->

    <!-- Start contact-page Area -->
    <section class="contact-page-area section-gap">
        <div class="container">
            <div class="row">
                <div class="map-wrap" style="width:100%; height: 445px;" id="map"></div>
                <div class="col-lg-4 d-flex flex-column address-wrap">
                    <div class="single-contact-address d-flex flex-row">
                        <div class="icon">
                            <span class="lnr lnr-home"></span>
                        </div>
                        <div class="contact-details">
                            <h5>Binghamton, New York</h5>
                            <p>
                                4343 Hinkle Deegan Lake Road
                            </p>
                        </div>
                    </div>
                    <div class="single-contact-address d-flex flex-row">
                        <div class="icon">
                            <span class="lnr lnr-phone-handset"></span>
                        </div>
                        <div class="contact-details">
                            <h5>00 (958) 9865 562</h5>
                            <p>Mon to Fri 9am to 6 pm</p>
                        </div>
                    </div>
                    <div class="single-contact-address d-flex flex-row">
                        <div class="icon">
                            <span class="lnr lnr-envelope"></span>
                        </div>
                        <div class="contact-details">
                            <h5>support@colorlib.com</h5>
                            <p>Send us your query anytime!</p>
                        </div>
                    </div>
                </div>

                <div class="col-lg-8">
                    <form class="form-area contact-form text-right" method="post">
                        {% csrf_token %}
                        <div class="row">
                            <div class="col-lg-6 form-group">
                                <input name="name" placeholder="Enter your name" onfocus="this.placeholder = ''"
                                       onblur="this.placeholder = 'Enter your name'"
                                       class="common-input mb-20 form-control" required="" type="text">

                                <input name="email" placeholder="Enter email address"
                                       pattern="[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{1,63}$"
                                       onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter email address'"
                                       class="common-input mb-20 form-control" required="" type="email">

                                <input name="subject" placeholder="Enter subject" onfocus="this.placeholder = ''"
                                       onblur="this.placeholder = 'Enter subject'"
                                       class="common-input mb-20 form-control" required="" type="text">
                            </div>
                            <div class="col-lg-6 form-group">
                                <textarea class="common-textarea form-control" name="message"
                                          placeholder="Enter Messege" onfocus="this.placeholder = ''"
                                          onblur="this.placeholder = 'Enter Messege'" required=""></textarea>
                            </div>
                            <div class="col-lg-12">
                                <div class="alert-msg" style="text-align: left;"></div>
                                <button class="genric-btn primary" style="float: right;">Send Message</button>
                            </div>
                        </div>
                    </form>

                </div>
                {% if messages %}
                    <ul class="messages">
                        {% for message in messages %}
                            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                        {% endfor %}
                    </ul>
                {% endif %}
            </div>
        </div>
    </section>
    <!-- End contact-page Area -->

{% endblock %}